In [5]:
import os

print(os.getcwd())

C:\Users\hp

In [6]:
import pandas as pd

df = pd.read_csv(r"C:\Users\hp\Downloads\Online_Retail.csv")

print(df.head())

  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6

           InvoiceDate  UnitPrice  CustomerID         Country
0  2010-12-01 08:26:00       2.55     17850.0  United Kingdom
1  2010-12-01 08:26:00       3.39     17850.0  United Kingdom
2  2010-12-01 08:26:00       2.75     17850.0  United Kingdom
3  2010-12-01 08:26:00       3.39     17850.0  United Kingdom
4  2010-12-01 08:26:00       3.39     17850.0  United Kingdom

In [7]:
df.shape

(20000, 8)

In [8]:
df.isnull().sum()

InvoiceNo         0
StockCode         0
Description      71
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID     6653
Country           0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(315)

In [10]:
df.dtypes

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

In [11]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

In [12]:
df.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
dtype: object

In [13]:
df["Quantity"].min()

-9360

In [14]:
df["UnitPrice"].min()

0.0

In [15]:
print((df["Quantity"] < 0).sum())

print((df["UnitPrice"] == 0).sum())

309
137

In [16]:
df[ df["Quantity"] < 0 ].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom

In [17]:
df[df["UnitPrice"] == 0].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom

In [18]:
df.isnull().sum()

InvoiceNo         0
StockCode         0
Description      71
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID     6653
Country           0
dtype: int64

In [19]:
df[df["Description"].isnull()].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom

In [20]:
df[df["Description"].isnull() & df["CustomerID"].isnull()].shape

(71, 8)

In [21]:
df = df.dropna(subset=["Description"])

In [22]:
df.shape

(19929, 8)

In [23]:
df["CustomerID"].isnull().sum()

np.int64(6582)

In [24]:
df.duplicated().sum()

np.int64(315)

In [25]:
df = df.drop_duplicates()

In [26]:
df.duplicated().sum()

np.int64(0)

In [27]:
(df["Quantity"] < 0).sum()

np.int64(265)

In [28]:
(df["UnitPrice"] == 0).sum()

np.int64(65)

In [29]:
df[df["UnitPrice"] == 0].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
6391,536941,22734,amazon,20,2010-12-03 12:08:00,0.0,NaN,United Kingdom
6392,536942,22139,amazon,15,2010-12-03 12:08:00,0.0,NaN,United Kingdom
7313,537032,21275,?,-30,2010-12-03 16:50:00,0.0,NaN,United Kingdom
9302,537197,22841,ROUND CAKE TIN VINTAGE GREEN,1,2010-12-05 14:02:00,0.0,12647.0,Germany
13217,537425,84968F,check,-20,2010-12-06 15:35:00,0.0,NaN,United Kingdom

In [30]:
(df["UnitPrice"] < 0).sum()

np.int64(0)

In [31]:
df.shape

(19614, 8)

In [32]:
(df["Quantity"] == 0).sum()

np.int64(0)

In [33]:
df["InvoiceNo"].astype(str).str.startswith("C").sum()

np.int64(261)

In [34]:
df[df["Quantity"] < 0].head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
239,C536391,21484,CHICK GREY HOT WATER BOTTLE,-12,2010-12-01 10:24:00,3.45,17548.0,United Kingdom
240,C536391,22557,PLASTERS IN TIN VINTAGE PAISLEY,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
241,C536391,22553,PLASTERS IN TIN SKULLS,-24,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
939,C536506,22960,JAM MAKING SET WITH JARS,-6,2010-12-01 12:38:00,4.25,17897.0,United Kingdom

In [35]:
df.to_csv("Online_Retail_Cleaned.csv", index=False)

In [36]:
df.shape

(19614, 8)

In [37]:
df[df["Quantity"] < 0].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom

In [38]:
(df["Quantity"] < 0).sum()

np.int64(265)

In [39]:
(df["UnitPrice"] == 0).sum()

np.int64(65)

In [40]:
df[df["UnitPrice"] == 0].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
6391,536941,22734,amazon,20,2010-12-03 12:08:00,0.0,NaN,United Kingdom
6392,536942,22139,amazon,15,2010-12-03 12:08:00,0.0,NaN,United Kingdom
7313,537032,21275,?,-30,2010-12-03 16:50:00,0.0,NaN,United Kingdom
9302,537197,22841,ROUND CAKE TIN VINTAGE GREEN,1,2010-12-05 14:02:00,0.0,12647.0,Germany
13217,537425,84968F,check,-20,2010-12-06 15:35:00,0.0,NaN,United Kingdom

In [41]:
df = df[df["UnitPrice"] > 0]

In [42]:
df.shape

(19549, 8)

In [43]:
(df["Quantity"] < 0).sum()

np.int64(261)

In [44]:
(df["UnitPrice"] < 0).sum()

np.int64(0)

In [45]:
df.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
dtype: object

In [46]:
df["CustomerID"].isnull().sum()

np.int64(6517)

In [47]:
df["CustomerID_Missing"] = df["CustomerID"].isnull()

In [48]:
df["CustomerID_Missing"].value_counts()

CustomerID_Missing
False    13032
True      6517
Name: count, dtype: int64

In [49]:
df = df.drop(columns=["CustomerID_Missing"])

In [52]:
df.shape

(19549, 8)

In [53]:
print(df.isnull().sum())
print("Duplicate rows:", df.duplicated().sum())

InvoiceNo         0
StockCode         0
Description       0
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID     6517
Country           0
dtype: int64
Duplicate rows: 0

In [55]:
df.to_csv("Online_Retail_Cleaned.csv", index=False)

In [56]:
import os
print(os.path.exists("Online_Retail_Cleaned.csv"))

True

In [57]:
readme = """# Online Retail Data Cleaning

## Dataset
Online Retail dataset

## Data Cleaning Steps
- Removed rows with missing Description.
- Removed duplicate records.
- Converted InvoiceDate to datetime.
- Removed records with zero UnitPrice.
- Checked negative Quantity values.
- Checked negative UnitPrice values.
- Identified missing CustomerID values and retained them.

## Final Dataset
- Rows: 19,549
- Columns: 8
- Duplicate rows: 0
- Missing CustomerID values: 6,517
"""

with open("README.md", "w") as file:
    file.write(readme)

In [58]:
import os
print(os.path.exists("README.md"))

True